from algebra import *
from areas_volumes import *
from arithmetic import *
from geometry import *
from graphics import *
from calculus import *
from probability import *
from std import *
from set_theory import *